version: "3.4"
services:
    gochain:
        build:
            context: ./gochain
        logging:
            driver: none
        volumes:
            - ${PWD}/config:/gochain/config
            - ${PWD}/data/gochain:/gochain/data
        ports:
            - 9080:9080
        environment: 
            - GOCHAIN_CONFIG=/gochain/config/gochain.server.json
            - GOCHAIN_DATA=/gochain/data/iconee
            - GOCHAIN_LOGFILE=/gochain/data/gochain.log
            - GOCHAIN_CLEAN_DATA=false
            - GOCHAIN_PROVISION_CONFIG=/gochain/provision/config
            - JAVAEE_BIN=/goloop/execman/bin/execman
            - PYEE_VERIFY_PACKAGE=true
    moonbeam:
        image: purestake/moonbeam:v0.9.6
        logging:
            driver: none
        volumes:
            - ${PWD}/data/moonbase_dev:/data/chains/moonbase_dev
        ports:
            - "9933:9933"
            - "9944:9944"
        command: ['--dev', '--ws-external', '--rpc-external', '--rpc-cors', 'all', '--base-path', '/data', '--ethapi', 'debug', '--sealing', '3000']
        user: root
    btp:
        build:
            context: .
        depends_on: 
            - gochain
            - moonbeam
        entrypoint: 
            - "/btpsimple/scripts/wait_for_it.sh"
            - "gochain:9080"
            - --
            - "/btpsimple/scripts/wait_for_it.sh"
            - "moonbeam:9933"
            - --
            - "/entrypoint.sh"
        volumes: 
            - ./scripts/deploy_javascore.sh:/btpsimple/scripts/deploy_javascore.sh
            - ./scripts/deploy_solidity.sh:/btpsimple/scripts/deploy_solidity.sh
            - ./helper:/btpsimple/helper
            - ${PWD}/config:/btpsimple/config
        environment: 
            - GOLOOPCHAIN=gochain
            - CONFIG_DIR=/btpsimple/config
            - RELAY_ENDPOINT=wss://kusama-rpc.polkadot.io
            - PARA_ENDPOINT=ws://moonbeam:9944