version: "3.4"
services:
  goloop:
    build:
      context: ./testnet/goloop
    environment:
      - GOLOOP_NODE_DIR=/goloop/data/goloop
      - GOLOOP_LOG_WRITER_FILENAME=/goloop/data/log/goloop.log
    volumes:
      - ${PWD}/build/config:/goloop/config
      - ${PWD}/build/data:/goloop/data
      - ${PWD}/build/data/log:/goloop/data/log
      - ${PWD}/testnet/goloop/scenario_test.sh:/goloop/bin/scenario_test.sh
    ports:
      - 9080:9080
    logging:
      driver: none
  btpsimple_src:
    # image: btpsimple:dev
    build:
      target: builder
      context: .
    entrypoint: ["sh", "/btpsimple/entrypoint.sh"]
    command:
      - "refresh"
      - "-c"
      - "refresh.yml"
    links:
      - goloop
    volumes:
      - ${PWD}/btp:/btpsimple/btp
      - ${PWD}/chain:/btpsimple/chain
      - ${PWD}/cmd:/btpsimple/cmd
      - ${PWD}/common:/btpsimple/common
      - ${PWD}/build/config:/btpsimple/config
      - ${PWD}/build/data:/btpsimple/data
      - ${PWD}/entrypoint.sh:/btpsimple/entrypoint.sh
    environment:
      - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_src
      - BTPSIMPLE_CONFIG=/btpsimple/config/src.config.json
      - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.src
      - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/src
      - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.dst
      - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/dst
      - BTPSIMPLE_OFFSET=/btpsimple/config/offset.src
      - BTPSIMPLE_KEY_STORE=/btpsimple/config/src.ks.json
      - BTPSIMPLE_KEY_SECRET=/btpsimple/config/src.secret
      - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/build/data/log/btpsimple_src.log
  # btpsimple_dst:
  #   # image: btpsimple:dev
  #   build:
  #     target: builder
  #     context: .
  #   entrypoint: ["sh", "/btpsimple/entrypoint.sh"]
  #   command:
  #     - "refresh"
  #     - "-c"
  #     - "refresh.yml"
  #   links:
  #     - goloop
  #   volumes:
  #     - ${PWD}/btp:/btpsimple/btp
  #     - ${PWD}/chain:/btpsimple/chain
  #     - ${PWD}/cmd:/btpsimple/cmd
  #     - ${PWD}/common:/btpsimple/common
  #     - ${PWD}/build/config:/btpsimple/config
  #     - ${PWD}/build/data:/btpsimple/data
  #     - ${PWD}/entrypoint.sh:/btpsimple/entrypoint.sh
  #   environment:
  #     - BTPSIMPLE_BASE_DIR=/btpsimple/data/btpsimple_dst
  #     - BTPSIMPLE_CONFIG=/btpsimple/config/dst.config.json
  #     - BTPSIMPLE_SRC_ADDRESS=/btpsimple/config/btp.dst
  #     - BTPSIMPLE_SRC_ENDPOINT=http://goloop:9080/api/v3/dst
  #     - BTPSIMPLE_DST_ADDRESS=/btpsimple/config/btp.src
  #     - BTPSIMPLE_DST_ENDPOINT=http://goloop:9080/api/v3/src
  #     - BTPSIMPLE_OFFSET=/btpsimple/config/offset.dst
  #     - BTPSIMPLE_KEY_STORE=/btpsimple/config/dst.ks.json
  #     - BTPSIMPLE_KEY_SECRET=/btpsimple/config/dst.secret
  #     - BTPSIMPLE_LOG_WRITER_FILENAME=/btpsimple/build/data/log/btpsimple_dst.log
